name: LRGSkyBlock-Core
version: 0.3.0
main: me.lrg.skyblock.core.LRGSkyBlockCore
api-version: "1.20"

author: LRG

softdepend:
  - PlaceholderAPI

commands:
  coins:
    description: Coinsを確認・操作するデバッグコマンド
    usage: /coins
    aliases:
      - coin